###
POST http://localhost:3000/products
Content-Type: application/json

{
      "name": "2",
      "description": "Product 1 description",
      "purchasePrice": 100,
      "stock": 10
}
###
POST http://localhost:3000/clients
Content-Type: application/json

{  
      "name": "Client 5",
      "email": "email",
      "document": "document",
      "street": "street",
      "number": "number",
      "complement": "complement",
      "city": "city",
      "state": "state",
      "zipCode": "zipCode" 
}

###
POST http://localhost:3000/checkout
Content-Type: application/json

{
   
}

###
POST http://localhost:3000/invoice
Content-Type: application/json

{
  "name": "Client 1",
  "document": "Document 1",
  "street": "Street 1",
  "number": "Number 1",
  "complement": "Complement 1",
  "city": "City 1",
  "state": "State 1",
  "zipCode": "ZipCode 1",
  "items": [
    {
      "id": "1",
      "name": "Item 1",
      "price": 100
    },
    {
      "id": "2",
      "name": "Item 2",
      "price": 200
    }
  ]
  
}
###
@invoiceId = 2a65d9a9-fc58-4699-8e05-27060ce635ad
###
GET http://localhost:3000/invoice/{{invoiceId}}





