###
POST http://localhost:3000/products
Content-Type: application/json

{
      "name": "2",
      "description": "Product 1 description",
      "purchasePrice": 100,
      "stock": 10
}
###
POST http://localhost:3000/store
Content-Type: application/json

{
      "name": "2",
      "description": "Product 1 description",
      "salesPrice": 100
}

###
GET http://localhost:3000/products
###
GET http://localhost:3000/store
###
@productId = ae96bc9d-7a7e-4644-91b7-fa1b953fb199
###
GET http://localhost:3000/products/{{productId}}
###
GET http://localhost:3000/store/{{productId}}

###
POST http://localhost:3000/clients
Content-Type: application/json

{  
      # "id": "1p",
      "name": "Client 7",
      "email": "email",
      "document": "document",
      "street": "street",
      "number": "number",
      "complement": "complement",
      "city": "city",
      "state": "state",
      "zipCode": "zipCode" 
}

###
@clientId = 9d40d241-56ba-46f9-81a3-79b4a447e442
###
GET http://localhost:3000/clients/{{clientId}}


###
POST http://localhost:3000/checkout
Content-Type: application/json

{
    
    "clientId": "{{clientId}}",
    "products": [
        {
            "productId": "{{productId}}"
        }
    ]
}

###
POST http://localhost:3000/invoice
Content-Type: application/json

{
  "name": "Client 1",
  "document": "Document 1",
  "street": "Street 1",
  "number": "Number 1",
  "complement": "Complement 1",
  "city": "City 1",
  "state": "State 1",
  "zipCode": "ZipCode 1",
  "items": [
    {
      "id": "1",
      "name": "Item 1",
      "price": 100
    },
    {
      "id": "2",
      "name": "Item 2",
      "price": 200
    }
  ]
  
}
###
@invoiceId = fb09af29-7647-49d4-9043-0616de2d7cb5
###
GET http://localhost:3000/invoice/{{invoiceId}}





