###
POST http://localhost:3000/products
Content-Type: application/json

{
      "name": "2",
      "description": "Product 1 description",
      "purchasePrice": 100,
      "stock": 10
}
###
POST http://localhost:3000/store
Content-Type: application/json

{
      "name": "2",
      "description": "Product 1 description",
      "salesPrice": 100
}

###
GET http://localhost:3000/products
###
GET http://localhost:3000/store
###
@productId = c3a01200-328c-4f5a-943f-67da7bc71ce7
###
GET http://localhost:3000/products/{{productId}}
###
GET http://localhost:3000/store/{{productId}}

###
POST http://localhost:3000/clients
Content-Type: application/json

{  
      # "id": "1p",
      "name": "Client 7",
      "email": "email",
      "document": "document",
      "street": "street",
      "number": "number",
      "complement": "complement",
      "city": "city",
      "state": "state",
      "zipCode": "zipCode" 
}

###
@clientId = deafd6fb-4a37-47d0-9f3d-961d0d693470
###
GET http://localhost:3000/clients/{{clientId}}


###
POST http://localhost:3000/checkout
Content-Type: application/json

{
    
    "clientId": "{{clientId}}",
    "products": [
        {
            "productId": "{{productId}}"
        }
    ]
}

###
POST http://localhost:3000/invoice
Content-Type: application/json

{
  "name": "Client 1",
  "document": "Document 1",
  "street": "Street 1",
  "number": "Number 1",
  "complement": "Complement 1",
  "city": "City 1",
  "state": "State 1",
  "zipCode": "ZipCode 1",
  "items": [
    {
      "id": "1",
      "name": "Item 1",
      "price": 100
    },
    {
      "id": "2",
      "name": "Item 2",
      "price": 200
    }
  ]
  
}
###
@invoiceId = 941636d9-164b-40d5-9db8-f4a288c61060
###
GET http://localhost:3000/invoice/{{invoiceId}}





